Третий урок, основное задание.
rusrich/thinknetica_react pull request #3
Opened 2020-08-09 13:08 UTC by rusrich

2020-08-10 12:43 UTC, index01d requested changes

2020-08-10 12:43 UTC, index01d commented on 01_homework/src/AuthContext.js
> +export default createContext({KEY})
в задании имелось ввиду значение в виде объекта с ключом currentUser:
`{ currentUser: { ...здесь будут даннные о пользователе }  }`

2020-08-10 12:43 UTC, index01d commented on 01_homework/src/AuthorCard/AuthorImageBlock.js
> +      author: {avatar}
можно было бы передать сюда просто avatar

2020-08-10 12:43 UTC, index01d commented on 01_homework/src/AuthorCard/AuthorInfoBlock.js
> +        <div><span style={styles.span}>Автор: </span>{name}</div>
чтобы не дублировать код можно было бы выделить ниже компонент Row с таким интерефейсом:

```
<Row label='Автор'>{name}</Row>
```

Тут то и пригодился бы children

2020-08-10 12:43 UTC, index01d commented on 01_homework/src/BookCard.js
> +        <ImageBlock {...this.props}/>
здесь можно было бы передать `avatar={author.avatar}`

2020-08-10 12:43 UTC, index01d commented on 01_homework/src/BookCard.js
> +        <ImageBlock {...this.props}/>
не стоит передавать неиспользуемые свойства, лучше явно указать только те свойства, которые нужны компоненту. Это упростит чтение и отладку кода (в дереве не будет лишних свойств)

2020-08-10 12:43 UTC, index01d commented on 01_homework/src/Feedback.js
> +            <div><label>Имя:</label></div>
Label закопировался.

Чтобы не дублировать код можно было бы выделить компонент

`<Field type='email' name='email' value={email} label='E-mail' onChange={this.handleChange} />`

Выбор textarea/input можно реализовать так:
```
const Field = (props) => {
  ...
  const Element = props.type === 'textarea' ? 'textarea' : 'input';
  ...
  return (
    <Element ... />
  );
}
```

2020-08-10 12:43 UTC, index01d commented on 01_homework/src/AuthContext.js
> +export default createContext({KEY})
или user как у тебя собственно и получилось. KEY здесь как таковой не нужен

2020-08-10 19:06 UTC, rusrich commented on 01_homework/src/Feedback.js
> +            <Field type='name' name='name' value={name} label='Имя' onChange={this.handleChange} />
Значение value не отображается в форме и не отслеживает изменения.
Если Field меняю на input, то отслеживание и отображение работает.
В интернете не нашел похожих примеров, сам пару часов потратил, не получилось исправить.
Подскажите или направьте, пожалуйста, как решать такие вещи.

2020-08-11 08:17 UTC, index01d requested changes

2020-08-11 08:17 UTC, index01d commented on 01_homework/src/AuthorCard/AuthorInfoBlock.js
> +        <span label='Автор'>{name}</span>
ожидалось что здесь будет

`<InfoOption  label='Автор'>{name}</InfoOption>`

а ниже
```js
const InfoOption = ({ label, children }) => (
  <div>
    <span style={styles.span}>{label}:</span> {children}
  </div>
);
```

2020-08-11 08:17 UTC, index01d commented on 01_homework/src/AuthorCard/AuthorInfoBlock.js
> +        <span label='Автор'>{name}</span>
наделять стандартные DOM-элементы новыми атрибутами (как тут label), а затем делать преобразование в цикле в другом компоненте это прямо жестокий антипаттерн

2020-08-11 08:17 UTC, index01d commented on 01_homework/src/Feedback.js
> +      <div><Element /></div>
здесь элемент поля ввода не получает атрибутов
`<Element name={props.name} onChange={props.onChange} value={props.value} />` исправит ситуацию.

Надо понимать что выше в 48 строке ты просто определяешь какой элемент отобразится input или textarea. Но все свойства ему нужно передать.

2020-08-12 12:57 UTC, index01d approved these changes

2020-08-12 15:53 UTC, merged